In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 0.57960725  2.53208549 -0.74090291 -1.71230936 -0.28060203]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.57960725  2.53208549 -0.74090291 -1.71230936 -0.28060203]


In [5]:
print(np.dot(a, a.T))

10.307079431320593


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-1.18578687]
 [-0.69791171]
 [ 2.18048598]
 [-0.58872075]
 [-0.07212683]]


In [7]:
print(a.T)

[[-1.18578687 -0.69791171  2.18048598 -0.58872075 -0.07212683]]


In [8]:
print(np.dot(a, a.T))

[[ 1.4060905   0.82757455 -2.58559165  0.69809733  0.08552705]
 [ 0.82757455  0.48708076 -1.52178671  0.41087511  0.05033816]
 [-2.58559165 -1.52178671  4.75451911 -1.28369734 -0.15727155]
 [ 0.69809733  0.41087511 -1.28369734  0.34659212  0.04246256]
 [ 0.08552705  0.05033816 -0.15727155  0.04246256  0.00520228]]
